"""生产域（production_）：产线/标注/质检/效率。

闭环第二环节，也是全湖写入最密集的域——采集 → 上云 → 打标签 → 前处理 → 标注 →
质检 → 后处理 → 交付共 14 个环节的状态，全部以 data_id 归集进 dwd_data_production_chain，
让「这批数据到哪一步了、哪个环节最慢、积压多少」从「问三个平台」变成一次主键查询。

域内表数：ODS 8 / DWD 5 / DWS 2 / ADS 1。
"""

from __future__ import annotations

from ...domains import DataDomain, Layer
from ..spec import Column as C
from ..spec import TableSpec

D = DataDomain.PRODUCTION

TABLES: list[TableSpec] = [
    # ------------------------------------------------------------------ ODS（8 张）
    TableSpec(
        name="ods_production_line_task",
        layer=Layer.ODS,
        domain=D,
        comment="产线任务（14 环节调度的最小派发单元）",
        source_system="产线平台 MySQL",
        bucket=4,
        primary_key=("line_task_id",),
        notes="Flink CDC 读 binlog 原样入湖，字段命名不规范之处留给 DWD 层修正",
        columns=[
            C("line_task_id", "STRING", "产线任务 ID", nullable=False),
            C("batch_id", "STRING", "所属批次 ID"),
            C("project_code", "STRING", "所属项目"),
            C("data_id", "STRING", "处理的数据单元 data_id（一级 ID）"),
            C(
                "stage_code",
                "STRING",
                "产线环节编码：upload/tagging/preprocess/annotate/qc/postprocess/deliver",
            ),
            C("pipeline_name", "STRING", "流水线名称"),
            C("algo_version", "STRING", "算法版本"),
            C("priority", "INT", "优先级，数值越小越先调度"),
            C("task_status", "STRING", "任务状态：pending/running/success/failed/canceled"),
            C("submit_time", "TIMESTAMP(3)", "提交时间"),
            C("start_time", "TIMESTAMP(3)", "开始时间"),
            C("end_time", "TIMESTAMP(3)", "结束时间"),
            C("operator", "STRING", "提交人账号"),
            C("retry_count", "INT", "重试次数"),
            C("error_message", "STRING", "失败信息"),
        ],
    ),
    TableSpec(
        name="ods_argo_workflow",
        layer=Layer.ODS,
        domain=D,
        comment="Argo 工作流运行元数据",
        source_system="Argo 元数据库",
        bucket=4,
        primary_key=("workflow_uid",),
        notes="产线各环节由 Argo Workflow 编排，此表是 run_id 与 K8s 实际执行的对照",
        columns=[
            C("workflow_uid", "STRING", "工作流唯一 ID（Argo UID）", nullable=False),
            C("workflow_name", "STRING", "工作流名称"),
            C("namespace", "STRING", "K8s 命名空间"),
            C("template_name", "STRING", "工作流模板名"),
            C("line_task_id", "STRING", "关联产线任务 ID"),
            C("run_id", "STRING", "三级 ID：对应的处理运行 ID"),
            C("phase", "STRING", "运行阶段：Pending/Running/Succeeded/Failed/Error"),
            C("started_at", "TIMESTAMP(3)", "工作流开始时间"),
            C("finished_at", "TIMESTAMP(3)", "工作流结束时间"),
            C("duration_sec", "DOUBLE", "运行时长（秒）"),
            C("node_count", "INT", "工作流节点数"),
            C("pod_count", "INT", "拉起的 Pod 数"),
            C("cpu_core", "DOUBLE", "申请 CPU 核数"),
            C("memory_gb", "DOUBLE", "申请内存（GB）"),
            C("parameters_json", "STRING", "入参快照（JSON），保证可重放"),
            C("exit_message", "STRING", "退出信息"),
        ],
    ),
    TableSpec(
        name="ods_annotation_task",
        layer=Layer.ODS,
        domain=D,
        comment="标注任务",
        source_system="标注平台",
        bucket=4,
        primary_key=("annotation_task_id",),
        columns=[
            C("annotation_task_id", "STRING", "标注任务 ID", nullable=False),
            C("batch_id", "STRING", "所属批次 ID"),
            C("project_code", "STRING", "所属项目"),
            C("data_id", "STRING", "待标注数据单元 data_id"),
            C("artifact_id", "STRING", "输入产物 ID（前处理产物）"),
            C("annotation_type", "STRING", "标注类型：2d_box/3d_box/lane/semantic_seg/tracking"),
            C("vendor_name", "STRING", "标注供应商"),
            C("annotator", "STRING", "标注员账号"),
            C("planned_object_count", "INT", "计划标注目标数"),
            C("task_status", "STRING", "任务状态：assigned/annotating/submitted/rework/done"),
            C("assign_time", "TIMESTAMP(3)", "派单时间"),
            C("start_time", "TIMESTAMP(3)", "开始标注时间"),
            C("finish_time", "TIMESTAMP(3)", "完成时间"),
            C("deadline", "TIMESTAMP(3)", "交付截止时间"),
            C("price_per_unit", "DECIMAL(12,4)", "标注单价"),
        ],
    ),
    TableSpec(
        name="ods_annotation_result",
        layer=Layer.ODS,
        domain=D,
        comment="标注结果（结果文件外置 OSS，湖仓只存元信息）",
        source_system="标注平台",
        bucket=4,
        primary_key=("annotation_result_id",),
        notes="大文件外置：标注结果 JSON 存 OSS，此表只存 key 与统计量",
        columns=[
            C("annotation_result_id", "STRING", "标注结果 ID", nullable=False),
            C("annotation_task_id", "STRING", "所属标注任务 ID"),
            C("data_id", "STRING", "数据单元 data_id"),
            C("artifact_id", "STRING", "标注产物 ID（二级 ID）"),
            C("frame_index", "INT", "帧序号"),
            C("object_count", "INT", "标注目标数"),
            C("label_object_key", "STRING", "标注结果文件对象存储 key"),
            C("annotation_version", "STRING", "标注结果版本"),
            C("annotator", "STRING", "标注员账号"),
            C("annotate_duration_sec", "DOUBLE", "标注耗时（秒）"),
            C("submit_time", "TIMESTAMP(3)", "提交时间"),
            C("self_check_score", "DOUBLE", "标注员自检得分"),
            C("is_rework", "BOOLEAN", "是否返工产出"),
            C("rework_reason", "STRING", "返工原因"),
            # ---- 入湖门禁判据（系列二第 6 篇《数据质量门禁设计》4.1 MySQL CDC · 业务库查「流程合规」）----
            # 这几列由标注平台随 CDC 报文带出、入湖瞬间即可判定，必须冗余落列：
            # 门禁按表粒度取字段，列不存在 = 规则恒取 NULL = 准入规则静默不生效。
            C(
                "qc_result_id",
                "STRING",
                "关联的质检结果 ID（冗余自 ods_qc_result.qc_result_id，跨源关联存在性判据）。"
                "对应 QG-CDC-001 标注质量准入：标注结果必须关联质检结论，质检缺失拒绝入湖",
            ),
            C(
                "qc_conclusion",
                "STRING",
                "冗余落列的质检结论（取值随 ods_qc_result.qc_conclusion）。"
                "对应 QG-CDC-002 标注质量准入：结论不为通过则拒绝入湖（L3 门禁动作「未过质检不入湖」）",
            ),
            C(
                "annotation_source",
                "STRING",
                "标注来源：manual/auto_label/pretrain_model/llm_prelabel。"
                "QG-CDC-003 的 when 前置条件字段——只有预标注来源才要求人工复核，"
                "该列缺失会让整条自动标注准入规则被跳过。"
                "⚠️ 原文未明确，本项目设计：原文只说「预标注结果必须人工审核」，"
                "没有给出区分来源的字段，更没有给取值字典；这四个取值由本项目枚举",
            ),
            C(
                "human_review_status",
                "STRING",
                "预标注结果的人工复核状态：pending/reviewed/approved/rejected。"
                "对应 QG-CDC-003 自动标注准入：大模型/离线模型预标注未经人工审核不得入训练数据集。"
                "⚠️ 原文未明确，本项目设计：原文只要求「经人工审核」这一动作，"
                "没说审核状态怎么留痕；本项目落成四态状态列，门禁按 reviewed/approved 放行",
            ),
            C(
                "task_status",
                "STRING",
                "标注任务状态：created/annotating/qc_pending/qc_passed/qc_rejected/delivered/cancelled。"
                "对应 QG-CDC-006 状态流转合法性校验（六维之有效性「状态流转合法」，P2 告警标记放行）",
            ),
            C(
                "prev_task_status",
                "STRING",
                "上一状态，QG-CDC-006 的 params.from_field——状态机要比对「旧 → 新」才判得了非法流转，"
                "只有 task_status 而没有它，这条规则同样永远判不出命中。"
                "⚠️ 原文未明确，本项目设计：原文只说「状态流转合法」，既没给状态机也没说前态如何取得；"
                "本项目选择在行上冗余一列前态，而不是让门禁回查上一版本——门禁热路径不挂重活",
            ),
        ],
    ),
    TableSpec(
        name="ods_qc_task",
        layer=Layer.ODS,
        domain=D,
        comment="质检任务",
        source_system="质检平台",
        bucket=4,
        primary_key=("qc_task_id",),
        columns=[
            C("qc_task_id", "STRING", "质检任务 ID", nullable=False),
            C("annotation_task_id", "STRING", "被质检的标注任务 ID"),
            C("batch_id", "STRING", "所属批次 ID"),
            C("project_code", "STRING", "所属项目"),
            C("data_id", "STRING", "被质检数据单元 data_id"),
            C("qc_type", "STRING", "质检类型：sampling/full/machine"),
            C("sample_ratio", "DOUBLE", "抽检比例"),
            C("planned_sample_count", "INT", "计划抽检目标数"),
            C("inspector", "STRING", "质检员账号"),
            C("qc_status", "STRING", "质检状态：assigned/checking/finished/canceled"),
            C("priority", "INT", "优先级"),
            C("assign_time", "TIMESTAMP(3)", "派单时间"),
            C("start_time", "TIMESTAMP(3)", "开始质检时间"),
            C("finish_time", "TIMESTAMP(3)", "完成时间"),
        ],
    ),
    TableSpec(
        name="ods_qc_result",
        layer=Layer.ODS,
        domain=D,
        comment="质检结果",
        source_system="质检平台",
        bucket=4,
        primary_key=("qc_result_id",),
        columns=[
            C("qc_result_id", "STRING", "质检结果 ID", nullable=False),
            C("qc_task_id", "STRING", "所属质检任务 ID"),
            C("annotation_result_id", "STRING", "被质检的标注结果 ID"),
            C("data_id", "STRING", "数据单元 data_id"),
            C("artifact_id", "STRING", "被质检产物 ID"),
            C("qc_conclusion", "STRING", "质检结论：pass/reject/rework"),
            C(
                "defect_type",
                "STRING",
                "缺陷类型：miss_label/wrong_label/box_inaccurate/attr_error",
            ),
            C("defect_count", "INT", "缺陷数"),
            C("checked_object_count", "INT", "实际抽检目标数"),
            C("accuracy_rate", "DOUBLE", "本次质检准确率"),
            C("inspector", "STRING", "质检员账号"),
            C("check_time", "TIMESTAMP(3)", "质检时间"),
            C("rework_round", "INT", "返工轮次，0 表示首检"),
            C("remark", "STRING", "质检备注"),
        ],
    ),
    TableSpec(
        name="ods_manual_operation_log",
        layer=Layer.ODS,
        name_omits_domain=True,
        domain=D,
        comment="人工操作日志（产线埋点事件流）",
        source_system="Kafka",
        bucket=4,
        primary_key=("operation_id",),
        notes="Kafka 通道入湖，保留回放能力；表名不含数据域段，域归属以本注册表声明为准",
        columns=[
            C("operation_id", "STRING", "操作流水 ID", nullable=False),
            C("operator", "STRING", "操作人账号"),
            C("operator_role", "STRING", "操作人角色：标注员/质检员/产线运维/数据负责人"),
            C(
                "operation_type",
                "STRING",
                "操作类型：rerun/invalidate/repriority/manual_fix/force_pass",
            ),
            C("target_type", "STRING", "操作对象类型：task/data/artifact/run"),
            C("target_id", "STRING", "操作对象 ID"),
            C("data_id", "STRING", "关联数据单元 data_id"),
            C("run_id", "STRING", "关联处理运行 run_id"),
            C("platform", "STRING", "来源平台：产线平台/标注平台/质检平台"),
            C("operation_time", "TIMESTAMP(3)", "操作时间"),
            C("before_value", "STRING", "操作前取值"),
            C("after_value", "STRING", "操作后取值"),
            C("reason", "STRING", "操作原因"),
            C("client_ip", "STRING", "来源 IP"),
        ],
    ),
    TableSpec(
        name="ods_production_kafka_event",
        layer=Layer.ODS,
        domain=D,
        comment="产线埋点事件流",
        source_system="Kafka",
        bucket=4,
        partition_by=("event_type",),
        primary_key=("event_id", "event_type"),
        notes=(
            "分区规则二：有明确业务分类过滤 → 按业务字段分区；事件类型间数据量差异极大。"
            "原则三：分区表主键必须包含分区字段 event_type"
        ),
        columns=[
            C("event_id", "STRING", "事件 ID", nullable=False),
            C(
                "event_type",
                "STRING",
                "事件类型：stage_start/stage_end/stage_fail/upload_done/deliver_done",
                nullable=False,
            ),
            C("data_id", "STRING", "关联数据单元 data_id"),
            C("artifact_id", "STRING", "关联产物 artifact_id"),
            C("run_id", "STRING", "关联处理运行 run_id"),
            C("line_task_id", "STRING", "关联产线任务 ID"),
            C("stage_code", "STRING", "产线环节编码"),
            C("event_status", "STRING", "事件携带的状态值"),
            C("event_time", "TIMESTAMP(3)", "事件发生时间"),
            C("producer_platform", "STRING", "事件产生平台"),
            C("kafka_topic", "STRING", "来源 Kafka topic"),
            C("kafka_partition", "INT", "Kafka 分区号，支持按位点回放"),
            C("kafka_offset", "BIGINT", "Kafka 位点"),
            C("trace_id", "STRING", "链路追踪 ID"),
            C("payload_json", "STRING", "原始事件体（JSON）"),
        ],
    ),
    # ------------------------------------------------------------------ DWD（5 张）
    TableSpec(
        name="dwd_data_production_chain",
        layer=Layer.DWD,
        name_omits_domain=True,
        domain=D,
        comment="数据生产主链路表（采集→上云→标注→质检→交付 14 环节状态归集）",
        bucket=16,
        primary_key=("data_id",),
        notes=(
            "全湖写入量最大的表，高并发 Upsert → bucket 16；Upsert 表且无明确分区维度 → 不分区。"
            "[a12] 第四章 Bucket 五档表点名本表作 16 档「超大表 / 高并发写入」的代表表；"
            "第六章 DDL 实战也以本表逐条对照五章规则（PK(data_id) / 不分区 / bucket 16 / "
            "changelog-producer=lookup / _ingest_time + update_time）；"
            "PK(data_id) 同时是主键原则一「业务主键优先」的原文示例。"
            "所有效率分析、瓶颈定位、血缘追溯的起点。表名不含数据域段（源文原名），域归属以本注册表为准"
        ),
        columns=[
            C("data_id", "STRING", "一级 ID：clip 级终身锚点，主链路主键", nullable=False),
            C("project_code", "STRING", "所属项目"),
            C("vehicle_code", "STRING", "采集车辆编码"),
            C("batch_id", "STRING", "所属交付批次"),
            C("collect_time", "TIMESTAMP(3)", "环节 1 采集完成时间"),
            C("upload_time", "TIMESTAMP(3)", "环节 2 上云完成时间"),
            C("tagging_time", "TIMESTAMP(3)", "环节 3 打标签完成时间"),
            C("preprocess_time", "TIMESTAMP(3)", "环节 4 前处理完成时间"),
            C("annotation_time", "TIMESTAMP(3)", "环节 5 标注完成时间"),
            C("qc_time", "TIMESTAMP(3)", "环节 6 质检完成时间"),
            C("postprocess_time", "TIMESTAMP(3)", "环节 7 后处理完成时间"),
            C("deliver_time", "TIMESTAMP(3)", "环节 8 交付完成时间"),
            C("current_stage", "STRING", "当前所处环节编码"),
            C("finished_stage_count", "INT", "已完成环节数（全链路共 14 环节）"),
            C("chain_status", "STRING", "链路状态：processing/delivered/blocked/invalid"),
            C("blocked_hour", "DOUBLE", "在当前环节的停留时长（小时），>48 视为积压"),
            C("bottleneck_stage", "STRING", "本条数据耗时最长的环节"),
            C("total_duration_hour", "DOUBLE", "采集→交付总耗时（小时）"),
            C("latest_artifact_id", "STRING", "最新交付产物 artifact_id"),
            C("dataset_id", "STRING", "交付进入的数据集 ID"),
        ],
    ),
    TableSpec(
        name="dwd_production_execution_detail",
        layer=Layer.DWD,
        domain=D,
        comment="产线执行明细（data_id × 环节 × 运行）",
        bucket=8,
        primary_key=("data_id", "stage_code", "run_id"),
        notes=(
            "原则二：复合主键表达完整粒度——同一 clip 的同一环节因重跑会有多次执行。"
            "大体量明细表 → bucket 8；[a12] 第四章 Bucket 五档表点名本表作 8 档"
            "「大体量明细表」的代表表"
        ),
        columns=[
            C("data_id", "STRING", "一级 ID：数据单元锚点", nullable=False),
            C("stage_code", "STRING", "产线环节编码", nullable=False),
            C("run_id", "STRING", "三级 ID：本次执行所属的处理运行", nullable=False),
            C("line_task_id", "STRING", "关联产线任务 ID"),
            C("project_code", "STRING", "所属项目"),
            C("stage_name", "STRING", "环节名称"),
            C("stage_order", "INT", "环节序号（1~14）"),
            C("exec_status", "STRING", "执行状态：success/failed/running/skipped"),
            C("start_time", "TIMESTAMP(3)", "执行开始时间"),
            C("end_time", "TIMESTAMP(3)", "执行结束时间"),
            C("duration_sec", "DOUBLE", "执行耗时（秒）"),
            C("queue_wait_sec", "DOUBLE", "排队等待时长（秒）"),
            C("input_artifact_id", "STRING", "输入产物 artifact_id"),
            C("output_artifact_id", "STRING", "输出产物 artifact_id"),
            C("algo_version", "STRING", "算法版本"),
            C("retry_count", "INT", "本环节重试次数"),
            C("executor", "STRING", "执行引擎：argo/flink/manual"),
            C("resource_core_hour", "DOUBLE", "资源消耗（核·时）"),
            C("error_code", "STRING", "失败错误码"),
            C("error_message", "STRING", "失败信息"),
        ],
    ),
    TableSpec(
        name="dwd_production_artifact_detail",
        layer=Layer.DWD,
        domain=D,
        comment="处理产物元信息（血缘核心）",
        bucket=16,
        primary_key=("artifact_id",),
        notes=(
            "血缘核心表，并发读写最高 → bucket 16。「处理版本化」在此落地："
            "重刷不覆盖，旧产物标 superseded 并指向新产物，新旧并存可对比可回滚。"
            "parent_artifact_id 冗余落表，作为 Neo4j 图库 DERIVED_FROM 边的对账兜底"
        ),
        columns=[
            C("artifact_id", "STRING", "二级 ID：处理产物，内嵌 data_id", nullable=False),
            C("data_id", "STRING", "一级 ID：所属采集单元，Badcase 回溯的落点"),
            C("parent_artifact_id", "STRING", "血缘父产物 ID（冗余落表，图库对账兜底）"),
            C("run_id", "STRING", "三级 ID：产出该产物的那一次运行"),
            C("stage", "STRING", "产物所属环节：align/slam/preprocess/annotate/qc/package"),
            C("artifact_type", "STRING", "产物类型：align/slam/annotation/qc_report/package"),
            C("algo_version", "STRING", "算法版本，与 artifact_id 中的段一致"),
            C("content_hash", "STRING", "内容哈希，重试幂等的来源"),
            C("artifact_status", "STRING", "产物状态：active/superseded/invalid"),
            C("superseded_by_artifact_id", "STRING", "被哪个新产物替代（重刷版本链）"),
            C(
                "param_snapshot_json",
                "STRING",
                "参数快照（JSON），可重放依据；大属性不进图库，血缘按 ID 回湖仓取",
            ),
            C("storage_uri", "STRING", "产物对象存储路径（大文件外置，湖仓只存元信息）"),
            C("file_count", "INT", "产物文件数"),
            C("file_size_bytes", "BIGINT", "产物总大小（字节）"),
            C("checksum_md5", "STRING", "产物校验和"),
            C("quality_score", "DOUBLE", "产物质量评分"),
            C("produce_time", "TIMESTAMP(3)", "产出时间"),
            C("project_code", "STRING", "所属项目"),
            C("vehicle_code", "STRING", "来源车辆编码"),
            C("dataset_id", "STRING", "被引用的数据集 ID（冗余，便于影响分析）"),
            C("reference_count", "INT", "血缘引用数，删除三重确认之一（>0 不可删）"),
        ],
    ),
    TableSpec(
        name="dwd_production_run_detail",
        layer=Layer.DWD,
        domain=D,
        comment="处理运行记录（含重跑信息）",
        bucket=4,
        primary_key=("run_id",),
        notes="绑定算法版本与参数快照，保证可重放；重跑不覆盖，通过 rerun_of_run_id 串成版本链",
        columns=[
            C("run_id", "STRING", "三级 ID：产线的一次执行", nullable=False),
            C("stage", "STRING", "运行环节，与 run_id 中的段一致"),
            C("line_task_id", "STRING", "关联产线任务 ID"),
            C("workflow_uid", "STRING", "Argo 工作流 UID"),
            C("project_code", "STRING", "所属项目"),
            C("batch_id", "STRING", "处理批次 ID"),
            C("data_id", "STRING", "关联数据单元 data_id（批量运行取代表 clip，逐条见执行明细）"),
            C("algo_version", "STRING", "算法版本"),
            C("image_version", "STRING", "容器镜像版本"),
            C("param_snapshot_json", "STRING", "参数快照（JSON），可重放的前提"),
            C("run_status", "STRING", "运行状态：running/success/failed/canceled"),
            C("start_time", "TIMESTAMP(3)", "开始时间"),
            C("end_time", "TIMESTAMP(3)", "结束时间"),
            C("duration_sec", "DOUBLE", "运行时长（秒）"),
            C("input_data_count", "INT", "输入数据单元数"),
            C("output_artifact_count", "INT", "产出产物数"),
            C(
                "input_artifact_ids",
                "STRING",
                "输入产物 ID 列表（冗余落表，图库 INPUT 边的对账源）",
            ),
            C(
                "output_artifact_ids",
                "STRING",
                "产出产物 ID 列表（冗余落表，图库 PRODUCED 边的对账源）",
            ),
            C("success_count", "INT", "成功数据单元数"),
            C("failed_count", "INT", "失败数据单元数"),
            C("is_rerun", "BOOLEAN", "是否为重跑"),
            C("rerun_of_run_id", "STRING", "重跑来源的 run_id"),
            C("rerun_reason", "STRING", "重跑原因：算法升级/数据修复/资源失败"),
            C("resource_core_hour", "DOUBLE", "资源消耗（核·时）"),
        ],
    ),
    TableSpec(
        name="dwd_manual_operation_detail",
        layer=Layer.DWD,
        name_omits_domain=True,
        domain=D,
        comment="人工操作明细（人工干预次数是效率分析的关键分母）",
        bucket=4,
        primary_key=("operation_id",),
        notes="表名不含数据域段（源文原名），域归属以本注册表声明为准",
        columns=[
            C("operation_id", "STRING", "操作流水 ID", nullable=False),
            C("data_id", "STRING", "关联数据单元 data_id"),
            C("artifact_id", "STRING", "关联产物 artifact_id"),
            C("run_id", "STRING", "关联处理运行 run_id"),
            C("line_task_id", "STRING", "关联产线任务 ID"),
            C("project_code", "STRING", "所属项目"),
            C("stage_code", "STRING", "被干预的产线环节编码"),
            C("operator", "STRING", "操作人账号"),
            C("operator_role", "STRING", "操作人角色"),
            C(
                "operation_type",
                "STRING",
                "操作类型：rerun/invalidate/repriority/manual_fix/force_pass",
            ),
            C("target_type", "STRING", "操作对象类型：task/data/artifact/run"),
            C("target_id", "STRING", "操作对象 ID"),
            C("operation_time", "TIMESTAMP(3)", "操作时间"),
            C("before_status", "STRING", "操作前状态"),
            C("after_status", "STRING", "操作后状态"),
            C("reason", "STRING", "操作原因"),
            C("is_override_gate", "BOOLEAN", "是否强制跳过质量门禁"),
            C("impact_data_count", "INT", "影响的数据单元数"),
            C("cost_minute", "DOUBLE", "人工耗时（分钟）"),
            C("platform", "STRING", "来源平台"),
        ],
    ),
    # ------------------------------------------------------------------ DWS（2 张）
    TableSpec(
        name="dws_production_efficiency_daily",
        layer=Layer.DWS,
        domain=D,
        comment="产线效率日指标（日期 × 项目 × 环节）",
        bucket=2,
        primary_key=("stat_date", "project_code", "stage_code"),
        notes=(
            "口径固化层：耗时/积压/吞吐的算法只在此处定义一次，ADS 与看板不再重复计算。"
            "[a12] 第四章 Bucket 五档表点名本表作 2 档「DWS 汇总表 / 小 ADS」的代表表"
        ),
        columns=[
            C("stat_date", "DATE", "统计日期", nullable=False),
            C("project_code", "STRING", "项目编码", nullable=False),
            C("stage_code", "STRING", "产线环节编码", nullable=False),
            C("stage_name", "STRING", "环节名称"),
            C("stage_order", "INT", "环节序号（1~14）"),
            C("input_data_count", "INT", "当日进入该环节的数据单元数"),
            C("output_data_count", "INT", "当日完成该环节的数据单元数"),
            C("delivered_data_count", "INT", "当日交付的数据单元数"),
            C("backlog_data_count", "INT", "日终积压数据单元数"),
            C("blocked_over_48h_count", "INT", "停留超 48 小时的数据单元数"),
            C("avg_duration_hour", "DOUBLE", "平均环节耗时（小时）"),
            C("p50_duration_hour", "DOUBLE", "P50 环节耗时（小时）"),
            C("p90_duration_hour", "DOUBLE", "P90 环节耗时（小时）"),
            C("max_duration_hour", "DOUBLE", "最长环节耗时（小时）"),
            C("avg_queue_wait_min", "DOUBLE", "平均排队时长（分钟）"),
            C("success_rate", "DOUBLE", "执行成功率"),
            C("rerun_count", "INT", "当日重跑次数"),
            C("manual_intervention_count", "INT", "当日人工干预次数"),
            C("throughput_per_hour", "DOUBLE", "小时吞吐（数据单元/小时）"),
            C("resource_core_hour", "DOUBLE", "当日资源消耗（核·时）"),
        ],
    ),
    TableSpec(
        name="dws_annotation_quality_daily",
        layer=Layer.DWS,
        domain=D,
        comment="标注质量日指标（日期 × 项目 × 标注类型 × 供应商）",
        bucket=2,
        primary_key=("stat_date", "project_code", "annotation_type", "vendor_name"),
        notes="原则二：复合主键表达完整粒度——供应商横向对比是标注质量治理的主视角",
        columns=[
            C("stat_date", "DATE", "统计日期", nullable=False),
            C("project_code", "STRING", "项目编码", nullable=False),
            C(
                "annotation_type",
                "STRING",
                "标注类型：2d_box/3d_box/lane/semantic_seg/tracking",
                nullable=False,
            ),
            C("vendor_name", "STRING", "标注供应商", nullable=False),
            C("annotation_task_count", "INT", "当日标注任务数"),
            C("annotated_data_count", "INT", "当日完成标注的数据单元数"),
            C("annotated_object_count", "BIGINT", "当日标注目标总数"),
            C("qc_sample_count", "INT", "质检抽检目标数"),
            C("qc_pass_count", "INT", "质检通过目标数"),
            C("qc_pass_rate", "DOUBLE", "质检通过率"),
            C("defect_count", "INT", "缺陷总数"),
            C("miss_label_count", "INT", "漏标数"),
            C("wrong_label_count", "INT", "错标数"),
            C("box_inaccurate_count", "INT", "框不准数"),
            C("attr_error_count", "INT", "属性错误数"),
            C("rework_task_count", "INT", "返工任务数"),
            C("rework_rate", "DOUBLE", "返工率"),
            C("avg_accuracy_rate", "DOUBLE", "平均标注准确率"),
            C("avg_annotate_duration_min", "DOUBLE", "单数据单元平均标注耗时（分钟）"),
            C("avg_qc_turnaround_hour", "DOUBLE", "标注提交到质检结论的平均周转（小时）"),
            C("cost_amount", "DECIMAL(18,2)", "当日标注成本金额"),
        ],
    ),
    # ------------------------------------------------------------------ ADS（1 张）
    TableSpec(
        name="ads_production_bottleneck_analysis",
        layer=Layer.ADS,
        domain=D,
        comment="产线瓶颈分析结果（零 JOIN，直接服务产线看板）",
        bucket=2,
        primary_key=("stat_date", "project_code", "stage_code"),
        notes=(
            "场景①落表链路终点：dwd_data_production_chain → dws_production_efficiency_daily → 本表。"
            "回答「这批数据到哪一步了 / 哪个环节最慢 / 积压多少」"
        ),
        columns=[
            C("stat_date", "DATE", "统计日期", nullable=False),
            C("project_code", "STRING", "项目编码", nullable=False),
            C("stage_code", "STRING", "产线环节编码", nullable=False),
            C("stage_name", "STRING", "环节名称"),
            C("stage_order", "INT", "环节序号（1~14）"),
            C("avg_duration_hour", "DOUBLE", "该环节平均耗时（小时）"),
            C("duration_ratio", "DOUBLE", "该环节耗时占全链路比例"),
            C("backlog_data_count", "INT", "积压数据单元数"),
            C("blocked_over_48h_count", "INT", "停留超 48 小时的数据单元数"),
            C("affected_batch_count", "INT", "受影响批次数"),
            C("throughput_per_hour", "DOUBLE", "小时吞吐（数据单元/小时）"),
            C("capacity_utilization", "DOUBLE", "产能利用率"),
            C("bottleneck_rank", "INT", "当日瓶颈排名，1 为最严重"),
            C("bottleneck_level", "STRING", "瓶颈等级：P0/P1/P2/P3"),
            C("root_cause", "STRING", "瓶颈根因：资源不足/人力不足/上游积压/算法失败"),
            C("suggestion", "STRING", "优化建议"),
            C("trend_vs_prev_day", "DOUBLE", "平均耗时环比变化率"),
            C("sample_data_id", "STRING", "代表性数据单元 data_id，供看板下钻"),
        ],
    ),
]
